flags: {}
user-message: ! 'Warning: Specified resolver could not satisfy all dependencies. Some
  external packages have been added as dependencies.

  You can suppress this message by removing it from stack.yaml

'
extra-package-dbs: []
packages:
- '.'
extra-deps:
- servant-jquery-0.2.2.1
- yaml-config-0.4.0
resolver: lts-8.5
